artifact_uri: file:///g:/Github_Projects/Pytorch_learning/YOLO/runs/mlflow/558457895820233549/4e398ee0b4f04294a2f6cf0bd41e380c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '558457895820233549'
lifecycle_stage: active
run_id: 4e398ee0b4f04294a2f6cf0bd41e380c
run_name: train3
source_name: ''
source_type: 4
source_version: ''
start_time: 1769521547476
status: 1
tags: []
user_id: Lenovo
