artifact_location: file:///g:/Github_Projects/Pytorch_learning/YOLO/runs/mlflow/0
creation_time: 1769521546942
experiment_id: '0'
last_update_time: 1769521546942
lifecycle_stage: active
name: Default
